nouns = nouns.concat([
    'case study',
    'cold call',
    'spreadsheet',
    'MBA',
    'pitch deck',
    'stakeholder',
    'consultant',
    'whiteboard',
    'latte',
    'networking event',
    'bulldog',
    'yale',
    'Handsome Dan',
    'Anjani-Jain',
    'Evans-Hall',
    'Charleys',
    'McNays',
    'CEOs',
    'Dean-Charles'
]);
