adjectives = adjectives.concat([
    'lowkey',
    'chopped',
    'mewing',
    'goated',
    'mid af',
    'alphas',
    'locked in',
    'baddies',
    'cooked',
    'peak',
    'chat',
    'hate to see me coming',
    'girlies',
    'do your thing',
    'techbros',
    'lore drop',
    'mother',
    'streets are saying',
    'irl',
    'rizzlers',
    'smash that',
    'side quest',
    'himbo',
    'rip',
  'speed running',
    'ight',
    'dip out',
  'bet',
    'fumble',
    'gigachad',
  'diva down',
    'goblin mode',
    'skibidi',
  'six seven'
]);
